name: make

on:
  push:
    branches: main
    paths: 'thermidity-avr/**'
  pull_request:
    branches: main
    paths: 'thermidity-avr/**'

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd $GITHUB_WORKSPACE/thermidity-avr && make
