name: make

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: thermidity-avr


    steps:
    - uses: actions/checkout@v3
    - uses: bazhenov/action-avr-make@v1.0
    
