name: make

on:
  push:
    branches: main
    paths: 'thermidity-avr/**'
  pull_request:
    branches: main
    paths: 'thermidity-avr/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: thermidity-avr

    steps:
    - uses: actions/checkout@v3
    - uses: bazhenov/action-avr-make@v1.0
    
